using InventorySystem.Core.Enums;
using InventorySystem.Core.Items.Quests;

namespace Lab3.Tests.Core.Items;

public class QuestItemTests
{
    [Fact(DisplayName = "Quest item has correct quest ID")]
    public void QuestItem_QuestId_IsCorrect()
    {
        var questItem = new QuestItem("Ancient Key", 1, RarityLevel.Premium, "Opens the sealed dungeon door", "QUEST-001", true);

        Assert.Equal("QUEST-001", questItem.QuestId);
    }

    [Fact(DisplayName = "Quest item interactable flag is set correctly")]
    public void QuestItem_IsInteractable_IsCorrect()
    {
        var questItem = new QuestItem("Ancient Key", 1, RarityLevel.Premium, "Opens the sealed dungeon door", "QUEST-001", true);

        Assert.True(questItem.IsInteractable);
    }

    [Fact(DisplayName = "Quest item non-interactable flag is set correctly")]
    public void QuestItem_IsNotInteractable_IsCorrect()
    {
        var questItem = new QuestItem("Sealed Letter", 1, RarityLevel.Ordinary, "A mysterious letter", "QUEST-002", false);

        Assert.False(questItem.IsInteractable);
    }

    [Fact(DisplayName = "Quest item Activate when interactable returns usage message")]
    public void QuestItem_Activate_Interactable_ReturnsUsageMessage()
    {
        var questItem = new QuestItem("Ancient Key", 1, RarityLevel.Premium, "Opens the sealed dungeon door", "QUEST-001", true);

        var result = questItem.Activate();

        Assert.Contains("Using quest item", result);
        Assert.Contains("Ancient Key", result);
    }

    [Fact(DisplayName = "Quest item Activate when not interactable returns error message")]
    public void QuestItem_Activate_NotInteractable_ReturnsErrorMessage()
    {
        var questItem = new QuestItem("Sealed Letter", 1, RarityLevel.Ordinary, "A mysterious letter", "QUEST-002", false);

        var result = questItem.Activate();

        Assert.Contains("cannot be used", result);
        Assert.Contains("QUEST-002", result);
    }

    [Fact(DisplayName = "Quest item GetDetails includes quest ID")]
    public void QuestItem_GetDetails_IncludesQuestId()
    {
        var questItem = new QuestItem("Ancient Key", 1, RarityLevel.Premium, "Opens the sealed dungeon door", "QUEST-001", true);

        var details = questItem.GetDetails();

        Assert.Contains("Quest ID: QUEST-001", details);
    }

    [Fact(DisplayName = "Quest item GetDetails shows interactable status")]
    public void QuestItem_GetDetails_ShowsInteractableStatus()
    {
        var interactableItem = new QuestItem("Ancient Key", 1, RarityLevel.Premium, "Opens the sealed dungeon door", "QUEST-001", true);
        var nonInteractableItem = new QuestItem("Sealed Letter", 1, RarityLevel.Ordinary, "A mysterious letter", "QUEST-002", false);

        var interactableDetails = interactableItem.GetDetails();
        var nonInteractableDetails = nonInteractableItem.GetDetails();

        Assert.Contains("Usable", interactableDetails);
        Assert.Contains("Not usable", nonInteractableDetails);
    }

    [Fact(DisplayName = "Quest item has auto-generated ID")]
    public void QuestItem_Id_IsAutoGenerated()
    {
        var questItem1 = new QuestItem("Ancient Key", 1, RarityLevel.Premium, "Opens the sealed dungeon door", "QUEST-001", true);
        var questItem2 = new QuestItem("Ancient Key", 1, RarityLevel.Premium, "Opens the sealed dungeon door", "QUEST-001", true);

        Assert.NotNull(questItem1.Id);
        Assert.NotNull(questItem2.Id);
        Assert.NotEqual(questItem1.Id, questItem2.Id);
    }

    [Fact(DisplayName = "Quest item has correct gear type")]
    public void QuestItem_GearType_IsQuestItem()
    {
        var questItem = new QuestItem("Ancient Key", 1, RarityLevel.Premium, "Opens the sealed dungeon door", "QUEST-001", true);

        Assert.Equal(GearType.QuestItem, questItem.GearType);
    }
}
